language: node_js
sudo: 'false'
dist: trusty
node_js: '9'
addons:
  firefox: latest
  chrome: stable
before_script: []
script:
  - xvfb-run polymer test
  - |-
    >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
env:
  global:
    - secure: >-
        FD8lx5vWmqT0+DznihRC0M5dcXTHBTwxXnZP9jMEuJeMP2coWGVfkzhV6L0SebQOw+5oHbgjMGhaOkhqPRFAV2NOYQN0viMHSLuX36WHZwUhSvy+tDTzqHaJytV4OZVs7fx3OUdwBP4Zv8WwbLs7xdpkp0sZ/xcu5MVswYzZ4VoESzNNVQWYjuzqph1LoCssUwCnmWhYukbggT/jqq43gMkBjX7gm7EzIUKh+t50P5R98cG/LKXHKUEsOxVx3PZWGPEcHy9atHDlUkFqoxID9Ttg+OLOcluQH5YKc9O+gzi2aJruYtEMLxgZsyteMWRqZFCyOAzh5pz1qatNW+h3pleKXhF9FkoSoTkHp2HPfCEtFdRd9P/XoXmmShgcY5dUdm1SdFXKQ9oTmw3wVDLO7GK6V+FsUE0254KPX1OaL/psXRvAZEm8jhxwV+B3QYsETgN4ZoKQe68pEut6lNcZu/IeUybSFxzRmJlVy8sGZsXl067mXQcPT5Q/IR8jlaEGhslH1t9adfnXGAdje/31EE+VPBJupKPbJMACUfel2yKLnRbvuH6Jj5jQv0izoBzpzqL6C8NMUmS/yV+0LZhd/5Ea/gpz708q5qRCuSKUbkUGEGzqQRLbOanyuN8jOSOxe3REkyx7dAK+E3fN9hglZSCivDvH6bfu4NtKz/vGpOA=
    - secure: >-
        GAbJwthVY24bG//yMD07C8yi/AIJdf3ApO4atzbNOLhPeVTsz1bNAoJHnb4Io8fGRXSKJlCUxwTDtlo9JsT3BUS0G/cV0TK1lPldgnS+l1T5e3AXJZdmsfOPxFfVdXi89lZ2YdCjtggvdlmfW+Poi4bskBX2wa3fLz6bK6iO/sG810vqo8fRxJNysVUxdQ/6fOfxyYwIAMj3dA+pUBvvXBhZBjY+Vaxq3BOpDwZ17yg+R0R4UVC1d6F26orTjYr1as2KgaOZgZUAXppH2BtEmGiNh40ZLevOAUniidwd6qanho967cHnnFcETb9nbIPA1AJp+uuVkrL2eBPu0fb7nmToPRbhysSvnLn/Hw3ue+XzY95qOaHmM99HsmcCAFgz6L5qYoORLHEdhT5GxtZdwLWSa2K5pabuIIoxlAoW4Yj6ngdJVqHkTv85a4vqmCChPBlX/I3Bb+zyVphWSIkwUfZ5icIlhHvUDnVtONfXDxhzGAwMN7kf6ednmHaJTH/pRyBWlbSupm3rrli5BWe4aEXpkbVgRi40NiwQPAVGt2YsR95IPw64wrAlhJTiw2f50FYUos59CHyPhRHLnp3yWDlXCRc0T/kfWUJn92vntaXjQIjygW1V1tlwcMzFt63Vs8yRVXNFvzDAdtUigL9v1NoFEZSzwdDqvAoDvEqltiE=
install:
  - npm install -g polymer-cli
  - polymer install --variants
cache:
  directories:
    - node_modules
